app_home:
  path: /accueil
  controller: App\Controller\HomeController::index
app_register:
  path: /inscription
  controller: App\Controller\RegistrationController::register
app_login:
  path: /connexion
  controller: App\Controller\SecurityController::login
app_logout:
  path: /deconnexion
  controller: App\Controller\SecurityController::logout
